# Generated by Django 4.2.5 on 2023-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('body', models.TextField(max_length=10000)),
            ],
        ),
    ]
